<?xml version="1.0"?>
<xacro:macro name="leg" params="prefix x y z hip_length thigh_length shin_length 
                                hip_upper hip_lower thigh_upper thigh_lower shin_upper shin_lower leg_width">
  <!-- Create 3 links and 3 joints named to match existing controllers: <PREFIX>_link1..3 and <PREFIX>_theta1..3 -->
  <link name="${prefix}_hip_link"/>
    <visual>
      <geometry><cylinder radius ="${leg_width/2}" length="${hip_length}"/></geometry>
    <visual>
  <link name="${prefix}_thigh_link"/>
  <link name="${prefix}_shin_link"/>

  <!-- Hip joint (theta1) -->
  <joint name="${prefix}_theta1" type="revolute">
    <parent link="base_link"/>
    <child link="${prefix}_hip_link"/>
    <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="5" velocity="5" lower="-1.5708" upper="1.5708"/>
  </joint>

  <!-- Thigh joint (theta2) -->
  <joint name="${prefix}_theta2" type="revolute">
    <parent link="${prefix}_hip_link"/>
    <child link="${prefix}_thigh_link"/>
    <!-- Origin places link2 a distance thigh_length along -Z from link1 -->
    <origin xyz="0 0 -${thigh_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="5" velocity="5" lower="-1.5708" upper="1.5708"/>
  </joint>

  <!-- Knee joint (theta3) -->
  <joint name="${prefix}_theta3" type="revolute">
    <parent link="${prefix}_thigh_link"/>
    <child link="${prefix}_shin_link"/>
    <!-- Origin places link3 a distance shin_length along -Z from link2 -->
    <origin xyz="0 0 -${shin_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="5" velocity="5" lower="0.0" upper="2.35619"/>
  </joint>


</xacro:macro>
